### ISSUE TITLE
Investigate how to submit Jobs to Yunikorn using dynamic settings

### ISSUE THREAD

**Issue by fmendezh** [gbif/stackable#21]
Currently pipelines and downloads are using Stackable Spark CRD templates for submitting Spark/Beam jobs using dynamic settings for executors, cores, memory and CPU, this should be tested and probably modified to assure those settings are understood by Yunikorn, an example of that config was committed for downloads in the [Airflow DAGs repository ](https://github.com/gbif/gbif-airflow-dags/blob/develop/dags/templates/spark_job_template_spark3_3.yaml#L90)

**Comment by zaultooz** [comment]
Dynamic configuration is enabled by providing these properties when submitting the SparkApplication:

https://github.com/gbif/gbif-airflow-dags/blob/develop/dags/templates/spark_job_template_spark3_5_0.yaml#L44-L49
